---
abstract: 'Validation module for nested array ,hash ,scalar  like FormValidator::Simple'
author:
  - 'S2 <s2otsa59@gmail.com>'
build_requires:
  Class::Load: 0
  Email::Valid: 0
  Hash::MultiValue: 0
  Test::Exception: 0
  Test::More: 0.98
  Time::Piece: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FormValidator-Simple-Struct
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  FormValidator::Simple::Struct:
    file: lib/FormValidator/Simple/Struct.pm
    version: 0.12
  FormValidator::Simple::Struct::AllowCharacter:
    file: lib/FormValidator/Simple/Struct/AllowCharacter.pm
    version: 0.12
  FormValidator::Simple::Struct::CharTypes:
    file: lib/FormValidator/Simple/Struct/CharTypes.pm
    version: 0.12
  FormValidator::Simple::Struct::Regex:
    file: lib/FormValidator/Simple/Struct/Regex.pm
    version: 0.12
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/S2/FormValidator-Simple-Struct/issues
  homepage: https://github.com/S2/FormValidator-Simple-Struct
  repository: https://github.com/S2/FormValidator-Simple-Struct.git
version: 0.12
x_contributors:
  - 'S2 <s2otsa@hotmail.com>'
  - 'sato sin <shinichiro@wano.co.jp>'
